# Generated by Django 3.0.5 on 2020-12-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('totalPoints', models.IntegerField()),
                ('market_val', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
