# Generated by Django 3.0.5 on 2020-12-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(default='', max_length=10)),
                ('traded_player_id', models.CharField(default='', max_length=10)),
                ('traded_player_name', models.CharField(default='', max_length=30)),
                ('value', models.IntegerField(default=-1)),
            ],
        ),
    ]
