# Generated by Django 3.0.5 on 2020-12-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickbase', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
