# Generated by Django 3.0.5 on 2020-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickbase', '0003_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traded_player_id', models.CharField(default='', max_length=10)),
                ('market_value_purchased', models.IntegerField(default=-1)),
            ],
        ),
    ]
