# Generated by Django 3.0.5 on 2021-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickbase', '0004_ownedplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_name',
            field=models.CharField(default='awt_group', max_length=30),
            preserve_default=False,
        ),
    ]
