# Generated by Django 3.0.5 on 2021-03-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickbase', '0005_transaction_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedplayer',
            name='user_name',
            field=models.CharField(default='awt_group', max_length=30),
            preserve_default=False,
        ),
    ]
